### ISSUE TITLE
Write SRS Documentation 

### ISSUE THREAD

**Issue by BoykoLazarov** [KilgharrahTW/QAFundTWP#11]
4.4. Reliability. 
4.5. Performance.
4.6. Supportability.
4.7. On-line User Documentation and Help System Requirements.
4.8. Licensing Requirements.

**Comment by Ivo-Nikolov** [comment]
[part4-4to4-8.docx](https://github.com/KilgharrahTW/QAFundTWP/files/226588/part4-4to4-8.docx)

**Comment by Ivo-Nikolov** [comment]
commit SRS part 4.4 to 4.8
