### ISSUE TITLE
Test user Profile functionalities.

### ISSUE THREAD

**Issue by GenaFrangina** [KilgharrahTW/QAFundTWP#5]
Testing user profile functionalities in site.

**Comment by ggsomnoev** [comment]
Few days ago I added materials to the docs about "user profile functionalities". I will be happy if you have time to review them.

**Comment by GenaFrangina** [comment]
Hi Georgi, 
I checked test cases and they are very good. You missed to add Pass status for 1-2 of them. Please check.
